/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author TICLAB4
 */
public class ViewBotonesListas extends javax.swing.JFrame {

    /**
     * Creates new form ViewBotonesListas
     */
    public ViewBotonesListas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelColores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cboColores = new javax.swing.JComboBox<>();
        cboRojo = new javax.swing.JComboBox<>();
        cboVerde = new javax.swing.JComboBox<>();
        cboAzul = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelColores.setBackground(new java.awt.Color(255, 204, 204));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        cboColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-selecciona opción-", "Rojo", "Azul", "Verde", "Amarillo", "Rosa", "Negro", "Blanco" }));
        cboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboColoresItemStateChanged(evt);
            }
        });
        cboColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboColoresActionPerformed(evt);
            }
        });
        cboColores.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboColoresPropertyChange(evt);
            }
        });

        cboRojo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-selecciona opcion-", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cboRojo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRojoItemStateChanged(evt);
            }
        });
        cboRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRojoActionPerformed(evt);
            }
        });

        cboVerde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-selecciona opcion-", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cboVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboVerdeItemStateChanged(evt);
            }
        });

        cboAzul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-selecciona opcion-", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        cboAzul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAzulItemStateChanged(evt);
            }
        });

        jLabel1.setText("rojo");

        jLabel2.setText("verde");

        jLabel3.setText("azul");

        javax.swing.GroupLayout panelColoresLayout = new javax.swing.GroupLayout(panelColores);
        panelColores.setLayout(panelColoresLayout);
        panelColoresLayout.setHorizontalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColoresLayout.createSequentialGroup()
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelColoresLayout.setVerticalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(13, 13, 13)
                        .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboColoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboColoresActionPerformed

    private void cboColoresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboColoresPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cboColoresPropertyChange

    private void cboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboColoresItemStateChanged
        // TODO add your handling code here:
       String color=cboColores.getSelectedItem().toString();
       System.out.println("Color" + color);
       
       switch(color.toLowerCase()){ ///para convertir todo a minusculas
           case "rojo":
                panelColores.setBackground(Color.red);
                break;
           case "azul":
                panelColores.setBackground(Color.blue);
                break;
           case "verde":
                panelColores.setBackground(Color.green);
                break;
           case "amarillo":
                panelColores.setBackground(Color.yellow);
                break;
           case "rosa":
                panelColores.setBackground(Color.pink);
                break;
           case "negro":
                panelColores.setBackground(Color.black);
                break;
           case "blanco":
                panelColores.setBackground(Color.white);
                break;
          case "morado":
                panelColores.setBackground(new Color(255,0,0));  //rojo //verde//azul
                break;
       }
      
    }//GEN-LAST:event_cboColoresItemStateChanged

    private void cboRojoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRojoItemStateChanged
        // TODO add your handling code here:
        String color=cboColores.getSelectedItem().toString();
       System.out.println("Color" + color);
       int numRojo= Integer.valueOf(cboRojo.getSelectedItem().toString());
       int numVerde=Integer.valueOf(cboVerde.getSelectedItem().toString());
       int numAzul= Integer.valueOf(cboAzul.getSelectedItem().toString());
       
        switch(numRojo){ ///para convertir todo a minusculas
            case 10:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 20:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 30:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 40:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 50:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 60:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 70:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 80:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 90:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 100:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
           
        }
    }//GEN-LAST:event_cboRojoItemStateChanged

    private void cboRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRojoActionPerformed

    private void cboVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboVerdeItemStateChanged
        // TODO add your handling code here:
        String color=cboColores.getSelectedItem().toString();
       System.out.println("Color" + color);
       int numRojo= Integer.valueOf(cboRojo.getSelectedItem().toString());
        int numVerde= Integer.valueOf(cboVerde.getSelectedItem().toString());
         int numAzul= Integer.valueOf(cboAzul.getSelectedItem().toString());
       
        switch(numVerde){ ///para convertir todo a minusculas
            case 10:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 20:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 30:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 40:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 50:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 60:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 70:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 80:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 90:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 100:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
        }
    }//GEN-LAST:event_cboVerdeItemStateChanged

    private void cboAzulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAzulItemStateChanged
        // TODO add your handling code here:
         String color=cboColores.getSelectedItem().toString();
       System.out.println("Color" + color);
       int numRojo= Integer.valueOf(cboRojo.getSelectedItem().toString());
        int numVerde= Integer.valueOf(cboVerde.getSelectedItem().toString());
         int numAzul= Integer.valueOf(cboAzul.getSelectedItem().toString());
       
        switch(numAzul){ ///para convertir todo a minusculas
            case 10:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 20:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 30:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 40:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 50:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 60:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
            case 70:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 80:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 90:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
             case 100:
                panelColores.setBackground(new Color(numRojo,numVerde,numAzul));
                break;
        }
    }//GEN-LAST:event_cboAzulItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBotonesListas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAzul;
    private javax.swing.JComboBox<String> cboColores;
    private javax.swing.JComboBox<String> cboRojo;
    private javax.swing.JComboBox<String> cboVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelColores;
    // End of variables declaration//GEN-END:variables
}
