/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class ViewRadioBotone extends javax.swing.JFrame {

    /**
     * Creates new form ViewRadioBotone
     */
    public ViewRadioBotone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelColor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        optionVerde = new javax.swing.JRadioButton();
        optionAzul = new javax.swing.JRadioButton();
        optionRojo = new javax.swing.JRadioButton();
        btnCambiarColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cambiando el color de fondo ");

        optionVerde.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(optionVerde);
        optionVerde.setForeground(new java.awt.Color(255, 255, 0));
        optionVerde.setText("Verde");

        optionAzul.setBackground(new java.awt.Color(51, 153, 255));
        buttonGroup1.add(optionAzul);
        optionAzul.setForeground(new java.awt.Color(0, 255, 0));
        optionAzul.setText("Azul");

        optionRojo.setBackground(new java.awt.Color(255, 0, 51));
        buttonGroup1.add(optionRojo);
        optionRojo.setForeground(new java.awt.Color(255, 255, 255));
        optionRojo.setText("Rojo");
        optionRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionRojoActionPerformed(evt);
            }
        });

        btnCambiarColor.setText("Cambiar color");
        btnCambiarColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelColorLayout.createSequentialGroup()
                    .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelColorLayout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColorLayout.createSequentialGroup()
                                    .addComponent(btnCambiarColor)
                                    .addGap(92, 92, 92))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelColorLayout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(optionRojo, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(optionVerde, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(optionAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelColorLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(optionRojo)
                    .addGap(18, 18, 18)
                    .addComponent(optionVerde)
                    .addGap(11, 11, 11)
                    .addComponent(optionAzul)
                    .addGap(18, 18, 18)
                    .addComponent(btnCambiarColor)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionRojoActionPerformed

    private void btnCambiarColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarColorMouseClicked
        // TODO add your handling code here:
        if (optionRojo.isSelected()) {
            panelColor.setBackground(new Color(255,100,10));
    }
       if (optionVerde.isSelected()){
           panelColor.setBackground(new Color(100,255,10));
        
    } 
       
       if (optionAzul.isSelected()) {
           panelColor.setBackground(new Color(10,10,255));
        
    }
    }//GEN-LAST:event_btnCambiarColorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRadioBotone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRadioBotone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRadioBotone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRadioBotone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRadioBotone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton optionAzul;
    private javax.swing.JRadioButton optionRojo;
    private javax.swing.JRadioButton optionVerde;
    private javax.swing.JPanel panelColor;
    // End of variables declaration//GEN-END:variables
}
